[{'author': u'Stephen King',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51h5g%2Bf9uwL._SX50_SY60_.jpg',
'title': u'11/22/63'},
{'author': u'Ha-Joon Chang',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51eWZe5nAuL._SX50_SY60_.jpg',
'title': u"23 Things They Don't Tell You About Capitalism"},
{'author': u'Timothy Ferriss',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51iGkLC6jhL._SX50_SY60_.jpg',
'title': u'The 4-Hour Work Week: Escape the 9-5, Live Anywhere and Join the New Rich'},
{'author': u'Stephen R. Covey',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51elX2wR3wL._SX50_SY60_.jpg',
'title': u'The 7 Habits of Highly Effective People'},
{'author': u'Erin Reese',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51pP7XFxLuL._SX50_SY60_.jpg',
'title': u'The Adventures of Bindi Girl: Diving Deep Into the Heart of India'},
{'author': u'Lewis Carroll',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51NBikxSWML._SX50_SY60_.jpg',
'title': u"Alice's Adventures in Wonderland"},
{'author': u'Brandon Sanderson',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51ewY4KqOmL._SX50_SY60_.jpg',
'title': u'The Alloy of Law: A Mistborn Novel'},
{'author': u'Jeffrey Archer',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51nU0WCz0sL._SX50_SY60_.jpg',
'title': u'As the Crow Flies'},
{'author': u'A.G. Riddle',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51NDeoTBFCL._SX50_SY60_.jpg',
'title': u'The Atlantis Gene: A Thriller (The Origin Mystery, Book 1)'},
{'author': u'A.G. Riddle',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51Q0LrQig5L._SX50_SY60_.jpg',
'title': u'The Atlantis Plague: A Thriller (The Origin Mystery, Book 2)'},
{'author': u'Ayn Rand',
'image': u'https://images-na.ssl-images-amazon.com/images/I/516YXpWRl2L._SX50_SY60_.jpg',
'title': u'Atlas Shrugged: (Centennial Edition)'},
{'author': u'Harlan Coben',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51OwlF3qVyL._SX50_SY60_.jpg',
'title': u'Back Spin (Myron Bolitar)'},
{'author': u'Gary Greenberg, Jeannie Hayden',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51D8QNQ9y-L._SX50_SY60_.jpg',
'title': u'Be Prepared: A Practical Handbook for New Dads'},
{'author': u'Julie A. Fast',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51DIXMITi1L._SX50_SY60_.jpg',
'title': u'Bipolar Happens! 35 Tips and Tricks to Manage Bipolar Disorder'},
{'author': u'Malcolm Gladwell',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51BMy-ZGqKL._SX50_SY60_.jpg',
'title': u'Blink: The Power of Thinking Without Thinking'},
{'author': u'Christopher McDougall',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51s889ttrnL._SX50_SY60_.jpg',
'title': u'Born to Run'},
{'author': u'Ken Wilber',
'image': u'https://images-na.ssl-images-amazon.com/images/I/41H9V7kHr5L._SX50_SY60_.jpg',
'title': u'A Brief History of Everything: Revised Edition'},
{'author': u'Robert E. Kraut, Yan Chen, Sara Kiesler, Moira Burke, Paul Resnick et al.',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51ISaa42-bL._SX50_SY60_.jpg',
'title': u'Building Successful Online Communities: Evidence-Based Social Design'},
{'author': u'Suzanne Collins',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51rMo8FtkDL._SX50_SY60_.jpg',
'title': u'Catching Fire (The Second Book of the Hunger Games)'},
{'author': u'Cesar Millan',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51GwwFbwS-L._SX50_SY60_.jpg',
'title': u"Cesar Millan's Short Guide to a Happy Dog: 98 Essential Tips and Techniques"},
{'author': u'Bryan Allain',
'image': u'https://images-na.ssl-images-amazon.com/images/I/41Cd7m-drZL._SX50_SY60_.jpg',
'title': u'Community Wins: 21 Thoughts on Building a Thriving Online Tribe'},
{'author': u'Geoffrey A. Moore',
'image': u'https://images-na.ssl-images-amazon.com/images/I/41kPh3XFqTL._SX50_SY60_.jpg',
'title': u'Crossing the Chasm: Marketing and Selling High-Tech Products to Mainstream Customers'},
{'author': u'David Sawyer McFarland',
'image': u'https://images-na.ssl-images-amazon.com/images/I/4108Yu00LfL._SX50_SY60_.jpg',
'title': u'CSS3: The Missing Manual'},
{'author': u'Harlan Coben',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51Wzs4xFu3L._SX50_SY60_.jpg',
'title': u'Darkest Fear: A Novel (Myron Bolitar)'},
{'author': u'Harlan Coben',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51qphUvBBXL._SX50_SY60_.jpg',
'title': u'Deal Breaker: The First Myron Bolitar Novel'},
{'author': u'Lee Child',
'image': u'https://images-na.ssl-images-amazon.com/images/I/41DRWsgr6SL._SX50_SY60_.jpg',
'title': u'Die Trying (Jack Reacher, No. 2)'},
{'author': u'Robert Jordan',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51rrvolHtDL._SX50_SY60_.jpg',
'title': u"The Dragon Reborn: Book Three of 'The Wheel of Time'"},
{'author': u'Daniel H. Pink',
'image': u'https://images-na.ssl-images-amazon.com/images/I/41mzE0eBCBL._SX50_SY60_.jpg',
'title': u'Drive: The Surprising Truth About What Motivates Us'},
{'author': u'Harlan Coben',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51R3zMqyfCL._SX50_SY60_.jpg',
'title': u'Drop Shot: A Myron Bolitar Novel'},
{'author': u'John Jantsch',
'image': u'https://images-na.ssl-images-amazon.com/images/I/41-h8hUDVkL._SX50_SY60_.jpg',
'title': u"Duct Tape Marketing: The World's Most Practical Small Business Marketing Guide"},
{'author': u'Elizabeth Gilbert',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51oU8954DFL._SX50_SY60_.jpg',
'title': u"Eat, Pray, Love: One Woman's Search for Everything Across Italy, India and Indonesia"},
{'author': u'Brandon Sanderson',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51Xx0cyVJhL._SX50_SY60_.jpg',
'title': u'Elantris'},
{'author': u'Daniel Goleman',
'image': u'https://images-na.ssl-images-amazon.com/images/I/41yNs2IPf1L._SX50_SY60_.jpg',
'title': u'Emotional Intelligence'},
{'author': u'Brandon Sanderson',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51BUzDTrzeL._SX50_SY60_.jpg',
'title': u"The Emperor's Soul"},
{'author': u'Sam Harris',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51jYSMrhGmL._SX50_SY60_.jpg',
'title': u'The End of Faith: Religion, Terror, and the Future of Reason'},
{'author': u'Lee Child',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51UZuDWi-WL._SX50_SY60_.jpg',
'title': u'The Enemy (Jack Reacher, No. 8)'},
{'author': u'J. D. Viharini',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51szjNe228L._SX50_SY60_.jpg',
'title': u'Enjoying India: The Essential Handbook'},
{'author': u'Nutan Publishing',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51PwKcAPOgL._SX50_SY60_.jpg',
'title': u'Everyday Hindi'},
{'author': u'Robert Jordan',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51-NVUtW9XL._SX50_SY60_.jpg',
'title': u"The Eye of the World: Book One of 'The Wheel of Time'"},
{'author': u'CJ Lyons',
'image': u'https://images-na.ssl-images-amazon.com/images/I/510J3mhb21L._SX50_SY60_.jpg',
'title': u'Face to Face: Hart and Drake, Book #3 (A Romantic Medical Suspense)'},
{'author': u'Harlan Coben',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51AjEtKktIL._SX50_SY60_.jpg',
'title': u'Fade Away (Myron Bolitar)'},
{'author': u'Phoef Sutton',
'image': u'https://images-na.ssl-images-amazon.com/images/I/41H6OlquF%2BL._SX50_SY60_.jpg',
'title': u'Fifteen Minutes to Live'},
{'author': u'Harlan Coben',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51y1v2RKHHL._SX50_SY60_.jpg',
'title': u'The Final Detail (Myron Bolitar)'},
{'author': u'Don Miguel Ruiz',
'image': u'https://images-na.ssl-images-amazon.com/images/I/61nVpYSpLdL._SX50_SY60_.jpg',
'title': u'The Four Agreements: A Practical Guide to Personal Freedom (A Toltec Wisdom Book)'},
{'author': u'Steven D. Levitt, Stephen J. Dubner',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51iHDdGxhsL._SX50_SY60_.jpg',
'title': u'Freakonomics Rev Ed: (and Other Riddles of Modern Life) (P.S.)'},
{'author': u'Richard Dawkins',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51LtxYvhKKL._SX50_SY60_.jpg',
'title': u'The God Delusion'},
{'author': u'Neil Gaiman, Terry Pratchett',
'image': u'https://images-na.ssl-images-amazon.com/images/I/513s47o-wlL._SX50_SY60_.jpg',
'title': u'Good Omens'},
{'author': u'Robert Jordan',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51F4T%2BJuTwL._SX50_SY60_.jpg',
'title': u"The Great Hunt: Book Two of 'The Wheel of Time'"},
{'author': u'Lee Child',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51A0pHS-9wL._SX50_SY60_.jpg',
'title': u'The Hard Way (Jack Reacher, No. 10)'},
{'author': u'Brandon Sanderson',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51APuJ3A5YL._SX50_SY60_.jpg',
'title': u'The Hero of Ages: Book Three of Mistborn'},
{'author': u'Michael Oliver, www.NaturalSelling.com',
'image': u'https://images-na.ssl-images-amazon.com/images/I/41xVIuzD88L._SX50_SY60_.jpg',
'title': u'How To Sell Network Marketing Without Fear, Anxiety Or Losing Your Friends!'},
{'author': u'Suzanne Collins',
'image': u'https://images-na.ssl-images-amazon.com/images/I/41-LhxpWQGL._SX50_SY60_.jpg',
'title': u'The Hunger Games'},
{'author': u'Jonah Lehrer',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51ViC45LmOL._SX50_SY60_.jpg',
'title': u'Imagine: How Creativity Works'},
{'author': u'Carl Honore',
'image': u'https://images-na.ssl-images-amazon.com/images/I/41gpMPB3FmL._SX50_SY60_.jpg',
'title': u'In Praise of Slowness (Plus)'},
{'author': u'John P. (John Peter) Jones',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51GKZRX5YgL._SX50_SY60_.jpg',
'title': u'India, Its Life and Thought'},
{'author': u'James Gleick',
'image': u'https://images-na.ssl-images-amazon.com/images/I/514ToTCeWNL._SX50_SY60_.jpg',
'title': u'The Information: A History, a Theory, a Flood'},
{'author': u'Daniel Quinn',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51yw3%2Br5vnL._SX50_SY60_.jpg',
'title': u'Ishmael: An Adventure of the Mind and Spirit'},
{'author': u'Lee Child',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51WWtqMg9OL._SX50_SY60_.jpg',
'title': u'Jack Reacher: One Shot: A Novel'},
{'author': u'Douglas Crockford',
'image': u'https://images-na.ssl-images-amazon.com/images/I/511j6cza5bL._SX50_SY60_.jpg',
'title': u'JavaScript: The Good Parts'},
{'author': u'Jakob Jenkov',
'image': u'https://images-na.ssl-images-amazon.com/images/I/511zokJKQQL._SX50_SY60_.jpg',
'title': u'jQuery Compressed'},
{'author': u'Mark GOULSTON',
'image': u'https://images-na.ssl-images-amazon.com/images/I/419Raa4lM8L._SX50_SY60_.jpg',
'title': u'Just Listen: Discover the Secret to Getting Through to Absolutely Anyone'},
{'author': u'Joshua Hammer',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51T-Il3x5tL._SX50_SY60_.jpg',
'title': u"The Kalinka Affair: A Father's Hunt for His Daughter's Killer (Kindle Single)"},
{'author': u'Jeffrey Archer',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51smTjw2q4L._SX50_SY60_.jpg',
'title': u'Kane and Abel'},
{'author': u'Lee Child',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51zzGBqKVPL._SX50_SY60_.jpg',
'title': u'Killing Floor (Jack Reacher, No. 1)'},
{'author': u'Brandon Sanderson',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51mBZW3wUVL._SX50_SY60_.jpg',
'title': u'Legion'},
{'author': u'James Lee Burke',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51Oqs13uJfL._SX50_SY60_.jpg',
'title': u'Light of the World: A Dave Robicheaux Novel'},
{'author': u'Harlan Coben',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51wkhf11nRL._SX50_SY60_.jpg',
'title': u'Live Wire (Myron Bolitar)'},
{'author': u'Lonely Planet',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51bEvs2jKFL._SX50_SY60_.jpg',
'title': u'Lonely Planet India (Travel Guide)'},
{'author': u'Harlan Coben',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51sd1aCihDL._SX50_SY60_.jpg',
'title': u'Long Lost (Myron Bolitar)'},
{'author': u'Edie Claire',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51PVpnFfsRL._SX50_SY60_.jpg',
'title': u'Long Time Coming'},
{'author': u'Sam Harris',
'image': u'https://images-na.ssl-images-amazon.com/images/I/31BX0aEcV%2BL._SX50_SY60_.jpg',
'title': u'Lying (Kindle Single)'},
{'author': u'Jordan Mechner',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51RDVWX-X9L._SX50_SY60_.jpg',
'title': u'The Making of Prince of Persia'},
{'author': u'Viktor E. Frankl',
'image': u'https://images-na.ssl-images-amazon.com/images/I/41-6tJsCF%2BL._SX50_SY60_.jpg',
'title': u"Man's Search for Meaning"},
{'author': u'Michael Lopp',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51HtOhioRbL._SX50_SY60_.jpg',
'title': u'Managing Humans: Biting and Humorous Tales of a Software Engineering Manager'},
{'author': u'Brandon Sanderson',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51RLOm1XmeL._SX50_SY60_.jpg',
'title': u'Mistborn: The Final Empire'},
{'author': u'Suzanne Collins',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51uznysICiL._SX50_SY60_.jpg',
'title': u'Mockingjay (The Final Book of The Hunger Games)'},
{'author': u'Dean Koontz',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51-YPtqk3wL._SX50_SY60_.jpg',
'title': u'The Moonlit Mind: A Tale of Suspense (Kindle Single)'},
{'author': u'Daniel Quinn',
'image': u'https://images-na.ssl-images-amazon.com/images/I/41in6Ui%2BvUL._SX50_SY60_.jpg',
'title': u'My Ishmael'},
{'author': u'Dee Henderson',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51LioPJmF-L._SX50_SY60_.jpg',
'title': u"The Negotiator: 1 (O'Malley)"},
{'author': u'CJ Lyons',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51ktXsMbFgL._SX50_SY60_.jpg',
'title': u'Nerves of Steel: Hart and Drake, Book #1 (A Romantic Medical Suspense)'},
{'author': u'Marshall B. Rosenberg, Arun Gandhi',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51knCrizQLL._SX50_SY60_.jpg',
'title': u'Nonviolent Communication: A Language of Life: Life-Changing Tools for Healthy Relationships (Nonviolent Communication Guides)'},
{'author': u'Jeffrey Archer',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51qEm3wcSoL._SX50_SY60_.jpg',
'title': u'Not A Penny More, Not a Penny Less'},
{'author': u'Carl R. Rogers',
'image': u'https://images-na.ssl-images-amazon.com/images/I/41I6g6L38sL._SX50_SY60_.jpg',
'title': u'On Becoming a Person'},
{'author': u'Harlan Coben',
'image': u'https://images-na.ssl-images-amazon.com/images/I/511NeswcgfL._SX50_SY60_.jpg',
'title': u'One False Move (Myron Bolitar)'},
{'author': u'Harrison H. Owen',
'image': u'https://images-na.ssl-images-amazon.com/images/I/41GiBNG0pWL._SX50_SY60_.jpg',
'title': u'Open Space Technology'},
{'author': u'Ken Robinson',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51x0mFQwXSL._SX50_SY60_.jpg',
'title': u'Out of Our Minds: Learning to be Creative'},
{'author': u'Malcolm Gladwell',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51e-EvAjCrL._SX50_SY60_.jpg',
'title': u'Outliers: The Story of Success'},
{'author': u'Lee Child',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51LPK5FD4nL._SX50_SY60_.jpg',
'title': u'Persuader (Jack Reacher, No. 7)'},
{'author': u'Al Ries',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51GlEWDp4jL._SX50_SY60_.jpg',
'title': u'Positioning: The Battle for Your Mind'},
{'author': u'Jim Loehr, Tony Schwartz',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51suzQKpnbL._SX50_SY60_.jpg',
'title': u'The Power of Full Engagement: Managing Energy, Not Time, is the Key to High Performance and Personal Renewal'},
{'author': u'Eckhart Tolle',
'image': u'https://images-na.ssl-images-amazon.com/images/I/41VOePNHbSL._SX50_SY60_.jpg',
'title': u'The Power of Now: A Guide to Spiritual Enlightenment'},
{'author': u'Dan Ariely',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51lwfg5zKkL._SX50_SY60_.jpg',
'title': u'Predictably Irrational: The Hidden Forces that Shape Our Decisions'},
{'author': u'Niccolo Machiavelli',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51jgukmVyAL._SX50_SY60_.jpg',
'title': u'The Prince'},
{'author': u'Jeffrey Archer',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51lWg1fx9sL._SX50_SY60_.jpg',
'title': u'Prodigal Daughter'},
{'author': u'Harlan Coben',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51dRjKtQfSL._SX50_SY60_.jpg',
'title': u'Promise Me (Myron Bolitar)'},
{'author': u'Alfie Kohn',
'image': u'https://images-na.ssl-images-amazon.com/images/I/41c-wIYOo8L._SX50_SY60_.jpg',
'title': u"Punished by Rewards: The Trouble with Gold Stars, Incentive Plans, A's, Praise, and Other Bribes"},
{'author': u'Brad Blanton',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51e5XpVGccL._SX50_SY60_.jpg',
'title': u'Radical Honesty: How to Transform Your Life by Telling the Truth'},
{'author': u'Lee Child',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51lsYhS56JL._SX50_SY60_.jpg',
'title': u'Running Blind (Jack Reacher, No. 4)'},
{'author': u'Ash Maurya',
'image': u'https://images-na.ssl-images-amazon.com/images/I/413wjRk5XrL._SX50_SY60_.jpg',
'title': u"Running Lean: Iterate from Plan A to a Plan That Works (Lean (O'Reilly))"},
{'author': u'Harry Beckwith',
'image': u'https://images-na.ssl-images-amazon.com/images/I/41wiQ%2BSZngL._SX50_SY60_.jpg',
'title': u'Selling the Invisible: A Field Guide to Modern Marketing (Biz Books to Go)'},
{'author': u'James Clavell',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51P2stqfP4L._SX50_SY60_.jpg',
'title': u'Shogun'},
{'author': u'CJ Lyons',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51o1EafwUFL._SX50_SY60_.jpg',
'title': u'Sleight of Hand: Hart and Drake, Book #2 (A Romantic Medical Suspense)'},
{'author': u'Terry Pratchett',
'image': u'https://images-na.ssl-images-amazon.com/images/I/61ZaNSI3yqL._SX50_SY60_.jpg',
'title': u'Snuff: (Discworld Novel 39) (Discworld Novels)'},
{'author': u'Robert A. Heinlein',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51CDyLBhVAL._SX50_SY60_.jpg',
'title': u'Starship Troopers'},
{'author': u'Brandon Sanderson',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51ZgSuU3thL._SX50_SY60_.jpg',
'title': u'Steelheart (Reckoners)'},
{'author': u'Alice J. Wisler',
'image': u'https://images-na.ssl-images-amazon.com/images/I/41pxTgP-MPL._SX50_SY60_.jpg',
'title': u'Still Life in Shadows'},
{'author': u'Daniel Quinn',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51HY8Z7EHCL._SX50_SY60_.jpg',
'title': u'The Story of B'},
{'author': u'Vianna Stibal',
'image': u'https://images-na.ssl-images-amazon.com/images/I/41cWJlRfNxL._SX50_SY60_.jpg',
'title': u'ThetaHealing\xae: Diseases and Disorders'},
{'author': u'Daniel Kahneman',
'image': u'https://images-na.ssl-images-amazon.com/images/I/41shZGS-G%2BL._SX50_SY60_.jpg',
'title': u'Thinking, Fast and Slow'},
{'author': u'Simon Singh, Professor Edzard Ernst',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51zu%2Bo4rZJL._SX50_SY60_.jpg',
'title': u'Trick or Treatment?: Alternative Medicine on Trial'},
{'author': u'Lee Child',
'image': u'https://images-na.ssl-images-amazon.com/images/I/61wAtSKrq3L._SX50_SY60_.jpg',
'title': u'Tripwire (Jack Reacher, No. 3)'},
{'author': u'Mitch Albom',
'image': u'https://images-na.ssl-images-amazon.com/images/I/41ujrSFHmFL._SX50_SY60_.jpg',
'title': u'Tuesdays with Morrie'},
{'author': u'Suzanne Collins',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51%2Bfc-SeGoL._SX50_SY60_.jpg',
'title': u'The Underland Chronicles #1: Gregor the Overlander (The Underland Chorni)'},
{'author': u'Andy Borowitz',
'image': u'https://images-na.ssl-images-amazon.com/images/I/41hzVMZrfvL._SX50_SY60_.jpg',
'title': u'An Unexpected Twist (Kindle Single)'},
{'author': u'Claude Bouchard',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51XQs8xQD1L._SX50_SY60_.jpg',
'title': u'Vigilante (VIGILANTE Series)'},
{'author': u'Leo Tolstoy, Leo Tolstoi',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51AkqDXe44L._SX50_SY60_.jpg',
'title': u'War and Peace (Cambridge World Classics) Critical Edition (Annotated) (Complete Works of Leo Tolstoy / Complete Works of Leo Tolstoi)'},
{'author': u'Brandon Sanderson',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51yNKw2vXSL._SX50_SY60_.jpg',
'title': u'Warbreaker (Tor Fantasy)'},
{'author': u'Brandon Sanderson',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51hwqRSszcL._SX50_SY60_.jpg',
'title': u'The Way of Kings (Stormlight Archive, The)'},
{'author': u'David Deida',
'image': u'https://images-na.ssl-images-amazon.com/images/I/41NougVWGcL._SX50_SY60_.jpg',
'title': u'The Way of the Superior Man: A Spiritual Guide to Mastering the Challenges of Women, Work, and Sexual Desire'},
{'author': u'Hilary T. Smith',
'image': u'https://images-na.ssl-images-amazon.com/images/I/414XiRfTpoL._SX50_SY60_.jpg',
'title': u'Welcome to the Jungle: Everything You Ever Wanted to Know About Bipolar but Were Too Freaked Out to Ask'},
{'author': u'Brandon Sanderson',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51IXBiewaeL._SX50_SY60_.jpg',
'title': u'The Well of Ascension: Book Two of Mistborn'},
{'author': u'Cheryl Strayed',
'image': u'https://images-na.ssl-images-amazon.com/images/I/41SkqqIk1HL._SX50_SY60_.jpg',
'title': u'Wild (From Lost to Found on the Pacific Crest Trail)'},
{'author': u'Stephen King',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51I9ylkNDTL._SX50_SY60_.jpg',
'title': u'The Wind Through the Keyhole: A Dark Tower Novel (The Dark Tower)'},
{'author': u'Lee Child',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51AC9PPWB1L._SX50_SY60_.jpg',
'title': u'Without Fail (Jack Reacher, No. 6)'},
{'author': u'Danny Bent',
'image': u'https://images-na.ssl-images-amazon.com/images/I/51M0TTOOKML._SX50_SY60_.jpg',
'title': u"You've Gone Too Far This Time, Sir!"},
{'author': u'Robert M. Pirsig',
'image': u'https://images-na.ssl-images-amazon.com/images/I/31nqYwGSzgL._SX50_SY60_.jpg',
'title': u'Zen and the Art of Motorcycle Maintenance'}]